# -*- coding: utf-8 -*-
"""
Custom filters for the TorStatus website.

Filters here are used in more than one template in TorStatus.
"""
from django import template

register = template.Library()

"""Map ISO-3166-1-alpha-2 codes to ISO 3166 country names"""
__COUNTRY_MAP = {
        '': u'Unknown',
        'None': u'Unknown',
        'a1': u'Unknown',
        'a2': u'Unknown',
        'ad': u'Andorra',
        'ae': u'United Arab Emirates',
        'af': u'Afghanistan',
        'ag': u'Antigua & Barbuda',
        'ai': u'Anguilla',
        'al': u'Albania',
        'am': u'Armenia',
        'an': u'Netherlands Antilles',
        'ao': u'Angola',
        'aq': u'Antarctica',
        'ar': u'Argentina',
        'as': u'American Samoa',
        'at': u'Austria',
        'au': u'Australia',
        'aw': u'Aruba',
        'az': u'Azerbaijan',
        'ba': u'Bosnia and Herzegovina',
        'bb': u'Barbados',
        'bd': u'Bangladesh',
        'be': u'Belgium',
        'bf': u'Burkina Faso',
        'bg': u'Bulgaria',
        'bh': u'Bahrain',
        'bi': u'Burundi',
        'bj': u'Benin',
        'bm': u'Bermuda',
        'bn': u'Brunei Darussalam',
        'bo': u'Bolivia',
        'br': u'Brazil',
        'bs': u'Bahama',
        'bt': u'Bhutan',
        'bu': u'Burma',
        'bv': u'Bouvet Island',
        'bw': u'Botswana',
        'by': u'Belarus',
        'bz': u'Belize',
        'ca': u'Canada',
        'cc': u'Cocos (Keeling) Islands',
        'cf': u'Central African Republic',
        'cg': u'Congo',
        'ch': u'Switzerland',
        'ci': u'Côte D\'ivoire (Ivory Coast)',
        'ck': u'Cook Iislands',
        'cl': u'Chile',
        'cm': u'Cameroon',
        'cn': u'China',
        'co': u'Colombia',
        'cr': u'Costa Rica',
        'cs': u'Czechoslovakia',
        'cu': u'Cuba',
        'cv': u'Cape Verde',
        'cx': u'Christmas Island',
        'cy': u'Cyprus',
        'cz': u'Czech Republic',
        'dd': u'German Democratic Republic',
        'de': u'Germany',
        'dj': u'Djibouti',
        'dk': u'Denmark',
        'dm': u'Dominica',
        'do': u'Dominican Republic',
        'dz': u'Algeria',
        'ec': u'Ecuador',
        'ee': u'Estonia',
        'eg': u'Egypt',
        'eh': u'Western Sahara',
        'er': u'Eritrea',
        'es': u'Spain',
        'et': u'Ethiopia',
        'fi': u'Finland',
        'fj': u'Fiji',
        'fk': u'Falkland Islands (Malvinas)',
        'fm': u'Micronesia',
        'fo': u'Faroe Islands',
        'fr': u'France',
        'fx': u'France, Metropolitan',
        'ga': u'Gabon',
        'gb': u'United Kingdom',
        'gd': u'Grenada',
        'ge': u'Georgia',
        'gf': u'French Guiana',
        'gh': u'Ghana',
        'gi': u'Gibraltar',
        'gl': u'Greenland',
        'gm': u'Gambia',
        'gn': u'Guinea',
        'gp': u'Guadeloupe',
        'gq': u'Equatorial Guinea',
        'gr': u'Greece',
        'gs': u'South Georgia and the South Sandwich Islands',
        'gt': u'Guatemala',
        'gu': u'Guam',
        'gw': u'Guinea-Bissau',
        'gy': u'Guyana',
        'hk': u'Hong Kong',
        'hm': u'Heard & McDonald Islands',
        'hn': u'Honduras',
        'hr': u'Croatia',
        'ht': u'Haiti',
        'hu': u'Hungary',
        'id': u'Indonesia',
        'ie': u'Ireland',
        'il': u'Israel',
        'in': u'India',
        'io': u'British Indian Ocean Territory',
        'iq': u'Iraq',
        'ir': u'Islamic Republic of Iran',
        'is': u'Iceland',
        'it': u'Italy',
        'jm': u'Jamaica',
        'jo': u'Jordan',
        'jp': u'Japan',
        'ke': u'Kenya',
        'kg': u'Kyrgyzstan',
        'kh': u'Cambodia',
        'ki': u'Kiribati',
        'km': u'Comoros',
        'kn': u'St. Kitts and Nevis',
        'kp': u'Korea, Democratic People\'s Republic of',
        'kr': u'Korea, Republic of',
        'kw': u'Kuwait',
        'ky': u'Cayman Islands',
        'kz': u'Kazakhstan',
        'la': u'Lao People\'s Democratic Republic',
        'lb': u'Lebanon',
        'lc': u'Saint Lucia',
        'li': u'Liechtenstein',
        'lk': u'Sri Lanka',
        'lr': u'Liberia',
        'ls': u'Lesotho',
        'lt': u'Lithuania',
        'lu': u'Luxembourg',
        'lv': u'Latvia',
        'ly': u'Libyan Arab Jamahiriya',
        'ma': u'Morocco',
        'mc': u'Monaco',
        'md': u'Moldova, Republic of',
        'mg': u'Madagascar',
        'mh': u'Marshall Islands',
        'ml': u'Mali',
        'mm': u'Myanmar',
        'mn': u'Mongolia',
        'mo': u'Macau',
        'mp': u'Northern Mariana Islands',
        'mq': u'Martinique',
        'mr': u'Mauritania',
        'ms': u'Monserrat',
        'mt': u'Malta',
        'mu': u'Mauritius',
        'mv': u'Maldives',
        'mw': u'Malawi',
        'mx': u'Mexico',
        'my': u'Malaysia',
        'mz': u'Mozambique',
        'na': u'Nambia',
        'nc': u'New Caledonia',
        'ne': u'Niger',
        'nf': u'Norfolk Island',
        'ng': u'Nigeria',
        'ni': u'Nicaragua',
        'nl': u'Netherlands',
        'no': u'Norway',
        'np': u'Nepal',
        'nr': u'Nauru',
        'nt': u'Neutral Zone',
        'nu': u'Niue',
        'nz': u'New Zealand',
        'om': u'Oman',
        'pa': u'Panama',
        'pe': u'Peru',
        'pf': u'French Polynesia',
        'pg': u'Papua New Guinea',
        'ph': u'Philippines',
        'pk': u'Pakistan',
        'pl': u'Poland',
        'pm': u'St. Pierre & Miquelon',
        'pn': u'Pitcairn',
        'pr': u'Puerto Rico',
        'pt': u'Portugal',
        'pw': u'Palau',
        'py': u'Paraguay',
        'qa': u'Qatar',
        're': u'Réunion',
        'ro': u'Romania',
        'ru': u'Russian Federation',
        'rw': u'Rwanda',
        'sa': u'Saudi Arabia',
        'sb': u'Solomon Islands',
        'sc': u'Seychelles',
        'sd': u'Sudan',
        'se': u'Sweden',
        'sg': u'Singapore',
        'sh': u'St. Helena',
        'si': u'Slovenia',
        'sj': u'Svalbard & Jan Mayen Islands',
        'sk': u'Slovakia',
        'sl': u'Sierra Leone',
        'sm': u'San Marino',
        'sn': u'Senegal',
        'so': u'Somalia',
        'sr': u'Suriname',
        'st': u'Sao Tome & Principe',
        'su': u'Union of Soviet Socialist Republics',
        'sv': u'El Salvador',
        'sy': u'Syrian Arab Republic',
        'sz': u'Swaziland',
        'tc': u'Turks & Caicos Islands',
        'td': u'Chad',
        'tf': u'French Southern Territories',
        'tg': u'Togo',
        'th': u'Thailand',
        'tj': u'Tajikistan',
        'tk': u'Tokelau',
        'tm': u'Turkmenistan',
        'tn': u'Tunisia',
        'to': u'Tonga',
        'tp': u'East Timor',
        'tr': u'Turkey',
        'tt': u'Trinidad & Tobago',
        'tv': u'Tuvalu',
        'tw': u'Taiwan, Province of China',
        'tz': u'Tanzania, United Republic of',
        'ua': u'Ukraine',
        'ug': u'Uganda',
        'um': u'United States Minor Outlying Islands',
        'us': u'United States of America',
        'uy': u'Uruguay',
        'uz': u'Uzbekistan',
        'va': u'Vatican City State (Holy See)',
        'vc': u'St. Vincent & the Grenadines',
        've': u'Venezuela',
        'vg': u'British Virgin Islands',
        'vi': u'United States Virgin Islands',
        'vn': u'Viet Nam',
        'vu': u'Vanuatu',
        'wf': u'Wallis & Futuna Islands',
        'ws': u'Samoa',
        'yd': u'Democratic Yemen',
        'ye': u'Yemen',
        'yt': u'Mayotte',
        'yu': u'Yugoslavia',
        'za': u'South Africa',
        'zm': u'Zambia',
        'zr': u'Zaire',
        'zw': u'Zimbabwe',
        'zz': u'Unknown',
        }


@register.filter
def code_to_country(code):
    """
    Convert a two-letter country code to a full country name.

    >>> code_to_country('fr')
    u'France'

    @type code: C{string}
    @param bytes_ps: A two-letter country code.
    @rtype: C{string}
    @return: The name of the country that the two-letter country code
        represents.
    """
    try:
        return __COUNTRY_MAP[code.lower()]
    except:
        return u'Unknown'
